import os
print("=====================================")
print("           made by bad_boy           ")
print("   my telegram id: @Bad_boy_468      ")
print("=====================================")
print("Started!")
os.system("termux-setup-storage")
os.system("apt update -y && apt upgrade -y")
os.system("pkg install php -y ")
os.system("pkg insatll python -y ")
os.system("pkg indtall git -y  ")
os.system("pkg indtall golang -y ")
os.system("pkg indtall python2 -y ")
os.system("pkg install host -y ")
os.system("pkg install nano -y ")
os.system("pkg install havij -y ")
os.system("pkg install hydra -y ")
os.system("pkg install wireshark -y ")
os.system("pkg install cmatrix -y ")
os.system("pkg install figlet -y ")
os.system("pkg install wget -y ")
os.system("pkg install cowsay -y ")
os.system("pkg install toilet -y ")
os.system("pkg install ruby -y ")
os.system("pkg install help -y ")
os.system("pkg install lolcat -y ")
os.system("pkg install curl -y ")
os.system("pkg install wgetrc -y ")
os.system("pkg install unzip -y ")
os.system("pkg install openssh -y ")
os.system("pkg install tor -y ")
os.system("pkg install net-tools -y ")
os.system("pkg install unrar -y ")
os.system("pkg install clang -y ")
os.system("pkg install w3m -y ")
os.system("pkg install proot -y ")
os.system("pip2 install wget -y ")
os.system("pip2 install requests -y ")
os.system("clear")
print("all pakage is installed!!")
